// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rre
Rcpp::NumericVector rre(const Rcpp::NumericMatrix& sequence);
RcppExport SEXP extrapolatr_rre(SEXP sequenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type sequence(sequenceSEXP);
    __result = Rcpp::wrap(rre(sequence));
    return __result;
END_RCPP
}
// mpe
Rcpp::NumericVector mpe(const Rcpp::NumericMatrix& sequence);
RcppExport SEXP extrapolatr_mpe(SEXP sequenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type sequence(sequenceSEXP);
    __result = Rcpp::wrap(mpe(sequence));
    return __result;
END_RCPP
}
