// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rre
Rcpp::NumericVector rre(const Rcpp::NumericMatrix& sequence);
RcppExport SEXP extrapolatr_rre(SEXP sequenceSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type sequence(sequenceSEXP );
        Rcpp::NumericVector __result = rre(sequence);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// mpe
Rcpp::NumericVector mpe(const Rcpp::NumericMatrix& sequence);
RcppExport SEXP extrapolatr_mpe(SEXP sequenceSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type sequence(sequenceSEXP );
        Rcpp::NumericVector __result = mpe(sequence);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
