# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform reduced-rank extrapolation
#'
#' This method removes any geometric terms from a sequence, leaving
#' you with the limit.  Note, as in the examples, that it will happily
#' remove divergent sequences.  This is a feature rather than a bug.
#' @param sequence a matrix, the columns of which are the sequence to
#'        accelerate
#' @return the RRE limit
#' @examples
#' ind <- seq_len(5)
#' vals <- 0.5^(ind - 1)
#' rre(matrix(vals, nrow=1))
#' rre(rbind(vals, 2 + vals))
#' @export
rre <- function(sequence) {
    .Call('extrapolatr_rre', PACKAGE = 'extrapolatr', sequence)
}

#' Perform minimal polynomial extrapolation
#'
#' This method removes any geometric terms from a sequence, leaving
#' you with the limit.  Note, as in the examples, that it will happily
#' remove divergent sequences.  This is a feature rather than a bug.
#' @param sequence a matrix, the columns of which are the sequence to
#'        accelerate
#' @return the MPE limit
#' @examples
#' ind <- seq_len(5)
#' vals <- 0.5^(ind - 1)
#' mpe(matrix(vals, nrow=1))
#' mpe(rbind(vals, 2 + vals))
#' @export
mpe <- function(sequence) {
    .Call('extrapolatr_mpe', PACKAGE = 'extrapolatr', sequence)
}

